# Organization and project keys are displayed in the right sidebar of the project homepage
sonar.organization=philippe-perrin-sonarsource-1
sonar.projectKey=philippe-perrin-sonarsource_test-repo

# Use ONLY if you have a scanner version smaller than 6.0
sonar.host.url=https://dev11.sc-dev11.io/

# --- optional properties ---

# Must be set if you want to use SonarQube Cloud's US instance. Defaults to empty, which corresponds to EU instasnce
# sonar.region=us

# defaults to project key
# sonar.projectName=My project
# defaults to 'not provided'
# sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=.

# Encoding of the source code. Default is default system encoding
# sonar.sourceEncoding=UTF-8